CREATE TYPE "ItPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'RESOLVED';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TABLE "Ticket" ADD COLUMN "itPriority" "ItPriority" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "Ticket" ADD COLUMN "assignedToUserId" INTEGER;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_assignedToUserId_fkey" FOREIGN KEY ("assignedToUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX "Ticket_assignedToUserId_idx" ON "Ticket"("assignedToUserId");
