import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import request from "supertest";
import { app } from "../../src/app.js";
import { getPrisma } from "../../src/prisma.js";
import { hashPassword } from "../../src/auth.js";
import { authenticatedAgent, csrfHeaders } from "../lab-02/auth-helper.js";
const prisma=getPrisma(), password="Admin Test Password 1"; let admin:any,secondAdmin:any,requester:any,staff:any,category:any,system:any,ownedTicket:any; const ids:number[]=[];
async function makeUser(role:string,suffix:string,extra:any={}){const u=await prisma.user.create({data:{name:`${role} Test`,email:`admin-api-${suffix}-${Date.now()}@example.com`,role:role as any,isActive:true,mustChangePassword:false,passwordHash:await hashPassword(password),...extra}});ids.push(u.id);return u;} async function adminSession(){return authenticatedAgent(admin.email,password);}
describe("Issue #23 Administrator User Management",()=>{beforeAll(async()=>{admin=await makeUser("ADMINISTRATOR","admin");secondAdmin=await makeUser("ADMINISTRATOR","second");requester=await makeUser("REQUESTER","requester");staff=await makeUser("IT_STAFF","staff");category=await prisma.category.create({data:{name:`Admin API Category ${Date.now()}`}});system=await prisma.relatedSystem.create({data:{name:`Admin API System ${Date.now()}`}});ownedTicket=await prisma.ticket.create({data:{ticketNumber:`ADM-${Date.now()}`,requesterId:requester.id,categoryId:category.id,relatedSystemId:system.id,summary:"Ticket owned for admin safety",description:"A sufficiently long ticket description for safety tests.",requestedPriority:"MEDIUM",itPriority:"MEDIUM"}});});afterAll(async()=>{await prisma.ticket.deleteMany({where:{id:ownedTicket?.id??-1}});await prisma.category.deleteMany({where:{id:category?.id??-1}});await prisma.relatedSystem.deleteMany({where:{id:system?.id??-1}});await prisma.user.deleteMany({where:{id:{in:ids}}});});
it("enforces administrator authorization and safe list fields",async()=>{expect((await request(app).get("/api/admin/users")).status).toBe(401);expect((await(await authenticatedAgent(requester.email,password)).agent.get("/api/admin/users")).status).toBe(403);expect((await(await authenticatedAgent(staff.email,password)).agent.get("/api/admin/users")).status).toBe(403);const s=await adminSession(),out=await s.agent.get("/api/admin/users").query({search:"requester",role:"REQUESTER"});expect(out.status).toBe(200);expect(out.body.some((u:any)=>u.id===requester.id)).toBe(true);expect(out.body[0]).not.toHaveProperty("passwordHash");expect(out.body[0]).not.toHaveProperty("session");});
it("creates users with normalized email, role, active state, and forced password change",async()=>{const s=await adminSession(),email=`NEW-ADMIN-${Date.now()}@EXAMPLE.COM`;const out=await s.agent.post("/api/admin/users").set(csrfHeaders(s.csrfToken)).send({name:"Created User",email,role:"REQUESTER",active:false,initialPassword:password});expect(out.status).toBe(201);expect(out.body.email).toBe(email.toLowerCase());expect(out.body.isActive).toBe(false);expect(out.body.mustChangePassword).toBe(true);expect(out.body.passwordHash).toBeUndefined();ids.push(out.body.id);const defaultEmail=`DEFAULT-ADMIN-${Date.now()}@example.com`;const defaultUser=await s.agent.post("/api/admin/users").set(csrfHeaders(s.csrfToken)).send({name:"Default Active User",email:defaultEmail,role:"REQUESTER",initialPassword:password});expect(defaultUser.status).toBe(201);expect(defaultUser.body.isActive).toBe(true);ids.push(defaultUser.body.id);expect((await s.agent.post("/api/admin/users").set(csrfHeaders(s.csrfToken)).send({name:"Dup",email,role:"REQUESTER",active:true,initialPassword:password})).status).toBe(409);expect((await s.agent.post("/api/admin/users").set(csrfHeaders(s.csrfToken)).send({name:"x",email:"bad",role:"NOPE",active:"yes",initialPassword:"short"})).status).toBe(422);});
it("validates and edits user fields, including duplicate email protection",async()=>{const s=await adminSession();expect((await s.agent.patch(`/api/admin/users/${requester.id}`).set(csrfHeaders(s.csrfToken)).send({role:"NOPE"})).status).toBe(422);expect((await s.agent.patch(`/api/admin/users/${requester.id}`).set(csrfHeaders(s.csrfToken)).send({active:"yes"})).status).toBe(422);expect((await s.agent.patch(`/api/admin/users/${requester.id}`).set(csrfHeaders(s.csrfToken)).send({email:admin.email})).status).toBe(409);const out=await s.agent.patch(`/api/admin/users/${requester.id}`).set(csrfHeaders(s.csrfToken)).send({name:"Renamed Requester",email:`renamed-${Date.now()}@example.com`,role:"REQUESTER",active:true});expect(out.status).toBe(200);expect(out.body.name).toBe("Renamed Requester");});
it("protects self-deactivation and assigned owners",async()=>{const s=await adminSession();expect((await s.agent.patch(`/api/admin/users/${admin.id}`).set(csrfHeaders(s.csrfToken)).send({active:false})).status).toBe(409);await prisma.ticket.update({where:{id:ownedTicket.id},data:{assignedToUserId:staff.id}});expect((await s.agent.patch(`/api/admin/users/${staff.id}`).set(csrfHeaders(s.csrfToken)).send({active:false})).status).toBe(409);expect((await s.agent.patch(`/api/admin/users/${staff.id}`).set(csrfHeaders(s.csrfToken)).send({role:"REQUESTER"})).status).toBe(409);});
it("AC-32 rejects deactivation of the last active Administrator",async()=>{const countSpy=vi.spyOn(prisma.user,"count").mockResolvedValue(1 as never);try{const s=await adminSession();const out=await s.agent.patch(`/api/admin/users/${admin.id}`).set(csrfHeaders(s.csrfToken)).send({active:false});expect(out.status).toBe(409);expect(out.body.error.code).toBe("ADMINISTRATOR_SAFETY_CONFLICT");const persisted=await prisma.user.findUnique({where:{id:admin.id},select:{isActive:true}});expect(persisted?.isActive).toBe(true);}finally{countSpy.mockRestore();}});
it("resets a target password, sets mustChangePassword, and revokes only target sessions",async()=>{const target=await makeUser("REQUESTER","reset");const targetSession=await authenticatedAgent(target.email,password),s=await adminSession(),newPassword="Reset Password For User 1",out=await s.agent.patch(`/api/admin/users/${target.id}/password`).set(csrfHeaders(s.csrfToken)).send({initialPassword:newPassword});expect(out.status).toBe(200);expect(out.body.mustChangePassword).toBe(true);expect(out.body.passwordHash).toBeUndefined();expect((await targetSession.agent.get("/api/auth/me")).status).toBe(401);expect((await s.agent.get("/api/auth/me")).status).toBe(200);const login=await authenticatedAgent(target.email,newPassword);expect((await login.agent.get("/api/auth/me")).body.user.mustChangePassword).toBe(true);expect((await s.agent.patch(`/api/admin/users/${target.id}/password`).set(csrfHeaders(s.csrfToken)).send({initialPassword:"short"})).status).toBe(422);expect((await s.agent.patch("/api/admin/users/999999/password").set(csrfHeaders(s.csrfToken)).send({initialPassword:newPassword})).status).toBe(404);});});
