import { Router } from "express";
import { getPrisma } from "../prisma.js";
import { attachAuth, clearSessionCookie, createSession, ensureCsrf, hashPassword, invalidateSession, requireAuth, requireCsrf, validPassword, verifyPassword } from "../auth.js";

const router = Router();
const safeUser = (u: { id: number; name: string; email: string; role: string; mustChangePassword: boolean }) => ({ id: u.id, name: u.name, email: u.email, role: u.role, mustChangePassword: u.mustChangePassword });
router.get("/api/auth/csrf", (req, res) => { const token = ensureCsrf(req, res); res.setHeader("Cache-Control", "no-store"); return res.json({ csrfToken: token }); });
router.post("/api/auth/login", async (req, res, next) => { try { if (!requireCsrf(req, res)) return; const { email, password } = req.body ?? {}; const user = typeof email === "string" ? await getPrisma().user.findUnique({ where: { email: email.trim().toLowerCase() } }) : null; if (!user || !user.isActive || typeof password !== "string" || !(await verifyPassword(password, user.passwordHash))) return res.status(401).json({ error: { code: "INVALID_CREDENTIALS", message: "Invalid email or password." } }); invalidateSession(req); const { csrfToken } = createSession(user.id, req, res); res.setHeader("X-CSRF-Token", csrfToken); return res.json({ user: safeUser(user) }); } catch (e) { next(e); } });
router.post("/api/auth/logout", attachAuth, requireAuth, (req, res) => { if (!requireCsrf(req, res)) return; invalidateSession(req); clearSessionCookie(res, req); res.status(204).send(); });
router.get("/api/auth/me", attachAuth, requireAuth, async (req, res) => { const u = await getPrisma().user.findUniqueOrThrow({ where: { id: req.auth!.userId } }); res.json({ user: safeUser(u) }); });
router.post("/api/auth/change-password", attachAuth, requireAuth, async (req, res, next) => { try { if (!requireCsrf(req, res)) return; const { currentPassword, newPassword } = req.body ?? {}; if (!validPassword(newPassword)) return res.status(400).json({ error: { code: "INVALID_PASSWORD", message: "Password must be 12-128 Unicode characters." } }); const user = await getPrisma().user.findUniqueOrThrow({ where: { id: req.auth!.userId } }); if (typeof currentPassword !== "string" || !(await verifyPassword(currentPassword, user.passwordHash))) return res.status(401).json({ error: { code: "INVALID_PASSWORD", message: "Current password is incorrect." } }); if (await verifyPassword(newPassword, user.passwordHash)) return res.status(400).json({ error: { code: "PASSWORD_REUSE", message: "New password must differ from the current password." } }); await getPrisma().user.update({ where: { id: user.id }, data: { passwordHash: await hashPassword(newPassword), mustChangePassword: false } }); return res.json({ message: "Password changed successfully.", mustChangePassword: false }); } catch (e) { next(e); } });
export default router;
