import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import AdminTicketInspection from "../../src/components/AdminTicketInspection";
import { claimStaffTicket, fetchAdminInternalNotes, fetchAdminTicketInspection, fetchUsers, updateAdminTicketPriority, updateStaffTicketOwner, updateStaffTicketStatus } from "../../src/api";

vi.mock("../../src/api", async () => ({ ...(await vi.importActual<typeof import("../../src/api")>("../../src/api")), fetchAdminInternalNotes: vi.fn(), fetchAdminTicketInspection: vi.fn(), fetchUsers: vi.fn(), updateAdminTicketPriority: vi.fn(), updateStaffTicketOwner: vi.fn(), claimStaffTicket: vi.fn(), updateStaffTicketStatus: vi.fn() }));
vi.mock("../../src/components/ActionsTakenPanel", () => ({ default: ({ ticketStatus, onTicketRefreshRequested }: { ticketStatus?: string; onTicketRefreshRequested?: () => void }) => <section><p>Actions Ticket status: {ticketStatus}</p><button type="button" onClick={onTicketRefreshRequested}>Refresh Ticket after Action conflict</button></section> }));
const ticket = { id: 7, ticketNumber: "TKT-7", summary: "Email issue", description: "Details", requestedPriority: "HIGH", itPriority: "HIGH", currentStatus: "NEW", version: 1, resolvedAt: null, resolutionReady: false, requester: { name: "Requester" }, category: { name: "Hardware" }, relatedSystem: { name: "Email" }, assignedTo: null, publicComments: [{ id: 1, body: "Public update", author: { name: "Staff" } }], internalNotes: [] } as any;
describe("Administrator Ticket Inspection", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(fetchAdminTicketInspection).mockResolvedValue(ticket); vi.mocked(fetchAdminInternalNotes).mockResolvedValue([{ id: 2, body: "Private note", author: { name: "Staff" } }] as any); vi.mocked(fetchUsers).mockResolvedValue([{ id: 9, name: "Staff", role: "IT_STAFF", isActive: true }] as any); vi.mocked(updateAdminTicketPriority).mockResolvedValue({ itPriority: "LOW", version: 2 }); vi.mocked(updateStaffTicketOwner).mockResolvedValue({ owner: { id: 9, name: "Staff", email: "staff@example.com" }, version: 2 }); vi.mocked(claimStaffTicket).mockResolvedValue({ owner: { id: 9, name: "Admin", email: "admin@example.com" }, version: 2 }); vi.mocked(updateStaffTicketStatus).mockResolvedValue({ id: 7, currentStatus: "OPEN", version: 2, updatedAt: "2026-01-02T00:00:00.000Z", resolvedAt: null }); });
  it("reads comments, internal notes, ownership controls, and requester advice", async () => { vi.mocked(fetchAdminTicketInspection).mockResolvedValue({ ...ticket, requesterResolutionIndicatedAt: "2026-01-02T00:00:00.000Z" }); render(<AdminTicketInspection ticketId={7} />); expect(await screen.findByText("Public update")).toBeInTheDocument(); expect(await screen.findByText("Private note")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Claim ticket" })).toBeInTheDocument(); expect(screen.getByText(/Requester indicated that the problem appears resolved/)).toBeInTheDocument(); expect(fetchAdminInternalNotes).toHaveBeenCalledWith(7); });
  it("updates IT Priority, owner, and a permitted Ticket status", async () => { render(<AdminTicketInspection ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("IT Priority"), { target: { value: "LOW" } }); fireEvent.click(screen.getByRole("button", { name: "Save IT Priority" })); await waitFor(() => expect(updateAdminTicketPriority).toHaveBeenCalledWith(7, "LOW", 1)); fireEvent.change(screen.getByLabelText("Owner"), { target: { value: "9" } }); fireEvent.click(screen.getByRole("button", { name: "Save owner" })); await waitFor(() => expect(updateStaffTicketOwner).toHaveBeenCalledWith(7, 9, 2)); fireEvent.change(screen.getByLabelText("Status"), { target: { value: "OPEN" } }); fireEvent.click(screen.getByRole("button", { name: "Save status" })); await waitFor(() => expect(updateStaffTicketStatus).toHaveBeenCalledWith(7, "OPEN", 2)); });
  it("refreshes the authoritative Ticket status after an Actions Taken conflict", async () => { vi.mocked(fetchAdminTicketInspection).mockResolvedValueOnce(ticket).mockResolvedValueOnce({ ...ticket, currentStatus: "CLOSED" }); render(<AdminTicketInspection ticketId={7} />); await screen.findByText("Actions Ticket status: NEW"); fireEvent.click(screen.getByRole("button", { name: "Refresh Ticket after Action conflict" })); await waitFor(() => expect(fetchAdminTicketInspection).toHaveBeenCalledTimes(2)); expect(screen.getByText("Actions Ticket status: CLOSED")).toBeInTheDocument(); });
});
