import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import StaffTicketDetail from "../../src/components/StaffTicketDetail";
import { ApiError, claimStaffTicket, fetchStaffTicketDetail, updateStaffTicketOwner, updateStaffTicketPriority, updateStaffTicketStatus } from "../../src/api";

vi.mock("../../src/api", async () => {
  const actual = await vi.importActual<typeof import("../../src/api")>("../../src/api");
  return { ...actual, claimStaffTicket: vi.fn(), fetchStaffTicketDetail: vi.fn(), updateStaffTicketOwner: vi.fn(), updateStaffTicketPriority: vi.fn(), updateStaffTicketStatus: vi.fn() };
});
vi.mock("../../src/components/ActionsTakenPanel", () => ({ default: ({ ticketStatus, onTicketRefreshRequested }: { ticketStatus?: string; onTicketRefreshRequested?: () => void }) => <section><p>Actions Ticket status: {ticketStatus}</p><button type="button" onClick={onTicketRefreshRequested}>Refresh Ticket after Action conflict</button></section> }));

const detail = {
  id: 7, ticketNumber: "TKT-7", createdAt: "2026-01-01T10:00:00Z", updatedAt: "2026-01-02T15:30:00Z", summary: "Email issue", description: "A detailed issue description.", requestedPriority: "HIGH", itPriority: "HIGH", currentStatus: "NEW", version: 1, resolvedAt: null, resolutionReady: false, category: { id: 1, name: "Hardware" }, relatedSystem: { id: 1, name: "Email" }, requester: { id: 3, name: "Requester", email: "requester@example.com" }, assignedTo: null, attachments: [], eligibleOwners: [{ id: 4, name: "Staff B", email: "b@example.com", role: "IT_STAFF" }], requesterResolutionIndicatedAt: null, requesterResolutionIndicatedByUserId: null,
} as any;

describe("StaffTicketDetail", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(fetchStaffTicketDetail).mockResolvedValue(detail); vi.mocked(claimStaffTicket).mockResolvedValue({ owner: { id: 9, name: "Current Staff", email: "staff@example.com" }, version: 2 }); vi.mocked(updateStaffTicketOwner).mockResolvedValue({ owner: { id: 4, name: "Staff B", email: "b@example.com" }, version: 2 }); vi.mocked(updateStaffTicketPriority).mockResolvedValue({ id: 7, requestedPriority: "HIGH", itPriority: "LOW", version: 2, updatedAt: "2026-01-02T00:00:00.000Z" }); vi.mocked(updateStaffTicketStatus).mockResolvedValue({ id: 7, currentStatus: "OPEN", version: 2, updatedAt: "2026-01-02T00:00:00.000Z", resolvedAt: null }); });
  it("renders detail fields and claim/reassign controls", async () => { render(<StaffTicketDetail ticketId={7} />); expect(await screen.findByText("TKT-7")).toBeInTheDocument(); expect(screen.getByText(/Jan 1, 2026/)).toBeInTheDocument(); expect(screen.getByText(/Jan 2, 2026/)).toBeInTheDocument(); expect(screen.getAllByText("Unassigned").length).toBeGreaterThan(0); expect(screen.getByRole("button", { name: "Claim ticket" })).toBeInTheDocument(); expect(screen.getByLabelText("Ticket owner")).toBeInTheDocument(); });
  it("claims and reassigns through the authenticated API helpers", async () => { render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.click(screen.getByRole("button", { name: "Claim ticket" })); await waitFor(() => expect(claimStaffTicket).toHaveBeenCalledWith(7, 1)); fireEvent.change(screen.getByLabelText("Ticket owner"), { target: { value: "4" } }); fireEvent.click(screen.getByRole("button", { name: "Save owner" })); await waitFor(() => expect(updateStaffTicketOwner).toHaveBeenCalledWith(7, 4, 2)); });
  it("updates priority and status through authenticated helpers", async () => { render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("IT Priority"), { target: { value: "LOW" } }); fireEvent.click(screen.getByRole("button", { name: "Save priority" })); await waitFor(() => expect(updateStaffTicketPriority).toHaveBeenCalledWith(7, "LOW", 1)); fireEvent.change(screen.getByLabelText("Ticket status"), { target: { value: "OPEN" } }); fireEvent.click(screen.getByRole("button", { name: "Save status" })); await waitFor(() => expect(updateStaffTicketStatus).toHaveBeenCalledWith(7, "OPEN", 2)); });
  it.each(["RESOLVED", "CLOSED", "CANCELLED"])("requires confirmation before %s", async (status) => { vi.spyOn(window, "confirm").mockReturnValue(false); render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("Ticket status"), { target: { value: status } }); fireEvent.click(screen.getByRole("button", { name: "Save status" })); await waitFor(() => expect(updateStaffTicketStatus).not.toHaveBeenCalled()); vi.restoreAllMocks(); });
  it("offers only transitions allowed from the current status", async () => { render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); const options = Array.from(screen.getByLabelText("Ticket status").querySelectorAll("option")).map((option) => option.textContent); expect(options).toEqual(["NEW", "OPEN", "CANCELLED"]); });
  it("hides Resolve until the documented Action gate is ready", async () => {
    vi.mocked(fetchStaffTicketDetail).mockResolvedValue({ ...detail, currentStatus: "IN_PROGRESS", resolutionReady: false });
    render(<StaffTicketDetail ticketId={7} />);
    await screen.findByText("TKT-7");
    expect(Array.from(screen.getByLabelText("Ticket status").querySelectorAll("option")).map((option) => option.textContent)).toEqual(["IN_PROGRESS", "WAITING_FOR_REQUESTER", "CANCELLED"]);
    expect(screen.getByText(/Resolve becomes available after/)).toBeInTheDocument();
  });

  it("updates displayed priority and status after successful mutations", async () => { render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("IT Priority"), { target: { value: "LOW" } }); fireEvent.click(screen.getByRole("button", { name: "Save priority" })); await waitFor(() => expect(screen.getByLabelText("IT Priority")).toHaveValue("LOW")); fireEvent.change(screen.getByLabelText("Ticket status"), { target: { value: "OPEN" } }); fireEvent.click(screen.getByRole("button", { name: "Save status" })); await waitFor(() => expect(screen.getByLabelText("Ticket status")).toHaveValue("OPEN")); });
  it("refreshes the authoritative Ticket status requested by Actions Taken", async () => { vi.mocked(fetchStaffTicketDetail).mockResolvedValueOnce(detail).mockResolvedValueOnce({ ...detail, currentStatus: "CLOSED" }); render(<StaffTicketDetail ticketId={7} />); await screen.findByText("Actions Ticket status: NEW"); fireEvent.click(screen.getByRole("button", { name: "Refresh Ticket after Action conflict" })); await waitFor(() => expect(fetchStaffTicketDetail).toHaveBeenCalledTimes(2)); expect(screen.getByText("Actions Ticket status: CLOSED")).toBeInTheDocument(); });
  it("surfaces mutation errors", async () => { vi.mocked(updateStaffTicketPriority).mockRejectedValueOnce(new Error("Priority update failed")); render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("IT Priority"), { target: { value: "LOW" } }); fireEvent.click(screen.getByRole("button", { name: "Save priority" })); expect(await screen.findByText("Priority update failed")).toBeInTheDocument(); });
  it("refreshes authoritative state while retaining a local selection after a stale workflow write", async () => { vi.mocked(fetchStaffTicketDetail).mockResolvedValueOnce(detail).mockResolvedValueOnce({ ...detail, currentStatus: "OPEN", version: 2 }); vi.mocked(updateStaffTicketStatus).mockRejectedValueOnce(new ApiError(409, "STALE_UPDATE", "The Ticket changed.")); render(<StaffTicketDetail ticketId={7} />); await screen.findByText("TKT-7"); fireEvent.change(screen.getByLabelText("Ticket status"), { target: { value: "CANCELLED" } }); vi.spyOn(window, "confirm").mockReturnValue(true); fireEvent.click(screen.getByRole("button", { name: "Save status" })); expect(await screen.findByText(/This Ticket changed/)).toBeInTheDocument(); await waitFor(() => expect(fetchStaffTicketDetail).toHaveBeenCalledTimes(2)); expect(screen.getByLabelText("Ticket status")).toHaveValue("CANCELLED"); vi.restoreAllMocks(); });
});
