import { Router } from "express";
import { getPrisma } from "./prisma.js";
import { hashPassword, requireCsrf, requirePasswordChanged, revokeUserSessions, validPassword } from "./auth.js";
const router = Router();
const roles = ["REQUESTER", "IT_STAFF", "ADMINISTRATOR"] as const;
const safe = { id: true, name: true, email: true, role: true, isActive: true, mustChangePassword: true, createdAt: true } as const;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const isRole = (v: unknown): v is typeof roles[number] => typeof v === "string" && (roles as readonly string[]).includes(v);
const isName = (v: unknown) => typeof v === "string" && v.trim().length >= 2 && v.trim().length <= 120;
const normEmail = (v: unknown) => typeof v === "string" ? v.trim().toLowerCase() : "";
function guard(req: any, res: any) { if (!req.auth) { res.status(401).json({ error: { code: "UNAUTHORIZED", message: "Authentication required." } }); return false; } if (!requirePasswordChanged(req, res)) return false;
  if (req.auth.role !== "ADMINISTRATOR") { res.status(403).json({ error: { code: "FORBIDDEN", message: "Administrator access required." } }); return false; } return true; }
function invalid(res: any, fields: Record<string,string>) { return res.status(422).json({ error: { code: "VALIDATION_ERROR", message: "Request validation failed.", fields } }); }
router.get("/api/admin/users", async (req,res)=>{ if(!guard(req,res))return; const unknown=Object.keys(req.query).find(k=>!['search','role'].includes(k)); if(unknown)return invalid(res,{[unknown]:"Unsupported query parameter."}); const search=typeof req.query.search==='string'?req.query.search.trim():""; const selected=req.query.role; if(search.length>100)return invalid(res,{search:"Search is too long."}); if(selected!==undefined&&!isRole(selected))return invalid(res,{role:"Invalid role."}); const users=await getPrisma().user.findMany({where:{...(selected?{role:selected}:{}),...(search?{OR:[{name:{contains:search,mode:'insensitive'}},{email:{contains:search,mode:'insensitive'}}]}:{})},orderBy:[{name:'asc'},{id:'asc'}],select:safe}); res.json(users); });
router.post("/api/admin/users", async(req,res)=>{if(!guard(req,res)||!requireCsrf(req,res))return; const b=req.body??{}, email=normEmail(b.email), f:Record<string,string>={}; if(!isName(b.name))f.name='Name must be 2 to 120 characters.'; if(!emailPattern.test(email))f.email='Valid email required.'; if(!isRole(b.role))f.role='Invalid role.'; if(b.active!==undefined&&typeof b.active!=='boolean')f.active='active must be boolean.'; if(!validPassword(b.initialPassword))f.initialPassword='Password must be 12 to 128 characters.'; if(Object.keys(f).length)return invalid(res,f); if(await getPrisma().user.findUnique({where:{email}}))return res.status(409).json({error:{code:'EMAIL_ALREADY_EXISTS',message:'Email already exists.'}}); const u=await getPrisma().user.create({data:{name:b.name.trim(),email,role:b.role,isActive:b.active===undefined?true:b.active,passwordHash:await hashPassword(b.initialPassword),mustChangePassword:true},select:safe}); res.status(201).json(u);});
router.patch("/api/admin/users/:id", async(req,res)=>{if(!guard(req,res)||!requireCsrf(req,res))return; const id=Number(req.params.id),b=req.body??{},p=getPrisma(),existing=await p.user.findUnique({where:{id},select:{id:true,role:true,isActive:true}}); if(!existing)return res.status(404).json({error:{code:'USER_NOT_FOUND',message:'User not found.'}}); const f:Record<string,string>={}; if(b.name!==undefined&&!isName(b.name))f.name='Name must be 2 to 120 characters.'; const email=b.email===undefined?undefined:normEmail(b.email); if(email!==undefined&&!emailPattern.test(email))f.email='Valid email required.'; if(b.role!==undefined&&!isRole(b.role))f.role='Invalid role.'; if(b.active!==undefined&&typeof b.active!=='boolean')f.active='active must be boolean.'; if(!Object.keys(b).some(k=>['name','email','role','active'].includes(k)))f.request='At least one editable field is required.'; if(Object.keys(f).length)return invalid(res,f); if(email&&await p.user.findUnique({where:{email},select:{id:true}}).then(found=>found&&found.id!==id))return res.status(409).json({error:{code:'EMAIL_ALREADY_EXISTS',message:'Email already exists.'}}); const nextRole=b.role??existing.role,nextActive=b.active??existing.isActive; const authUserId = req.auth?.userId; if(authUserId===id&&nextActive===false)return res.status(409).json({error:{code:'ADMINISTRATOR_SAFETY_CONFLICT',message:'Cannot deactivate yourself.'}}); if(existing.role==='ADMINISTRATOR'&&existing.isActive&&(nextRole!=='ADMINISTRATOR'||nextActive===false)&&await p.user.count({where:{role:'ADMINISTRATOR',isActive:true}})<=1)return res.status(409).json({error:{code:'ADMINISTRATOR_SAFETY_CONFLICT',message:'Last active Administrator cannot be removed.'}}); if((nextActive===false||nextRole==='REQUESTER')&&await p.ticket.count({where:{assignedToUserId:id}}))return res.status(409).json({error:{code:'TICKET_OWNER_SAFETY_CONFLICT',message:'Reassign owned Tickets first.'}}); const data:any={}; if(b.name!==undefined)data.name=b.name.trim(); if(email!==undefined)data.email=email; if(b.role!==undefined)data.role=b.role; if(b.active!==undefined)data.isActive=b.active; const u=await p.user.update({where:{id},data,select:safe}); res.json(u);});
router.patch("/api/admin/users/:id/password", async(req,res)=>{if(!guard(req,res)||!requireCsrf(req,res))return; const id=Number(req.params.id),password=req.body?.initialPassword; if(!validPassword(password))return invalid(res,{initialPassword:'Password must be 12 to 128 characters.'}); const p=getPrisma(); if(!await p.user.findUnique({where:{id},select:{id:true}}))return res.status(404).json({error:{code:'USER_NOT_FOUND',message:'User not found.'}}); const u=await p.user.update({where:{id},data:{passwordHash:await hashPassword(password),mustChangePassword:true},select:safe}); revokeUserSessions(id); res.json(u);});
export default router;
