import { useEffect, useRef, useState } from "react";
import { ApiError, createActionTaken, fetchActionsTaken, updateActionTaken, type ActionTaken, type ActionUserSummary, type AuthUser, type CreateActionTakenInput, type UpdateActionTakenInput } from "../api";
import ActionTakenForm from "./ActionTakenForm";
import Empty from "./Empty";
import ErrorState from "./ErrorState";
import Loading from "./Loading";

type Role = AuthUser["role"];
type ReviewMode = "ACTION_IMMUTABLE" | "TERMINAL_STALE" | null;
type Props = { ticketId: number; role: Role; ticketStatus?: string; assignees?: ActionUserSummary[] };

const isInactive = (status?: string) => ["RESOLVED", "CLOSED", "CANCELLED"].includes(status ?? "");
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Bangkok" }).format(new Date(value)) : "Not performed";
const followUp = (action: ActionTaken) => action.followUpRequired ? `Required${action.followUpNote ? `: ${action.followUpNote}` : ""}` : "Not required";

function Details({ action }: { action: ActionTaken }) {
  return <dl className="actions-taken__details"><div><dt>Action Creator</dt><dd>{action.createdBy.name}</dd></div><div><dt>Action Assignee</dt><dd>{action.assignedTo?.name ?? "Unassigned"}</dd></div><div><dt>Performed By</dt><dd>{action.performedBy?.name ?? "Not performed"}</dd></div><div><dt>Completed At</dt><dd>{formatDate(action.completedAt)}</dd></div><div><dt>Created At</dt><dd>{formatDate(action.createdAt)}</dd></div><div><dt>Updated At</dt><dd>{formatDate(action.updatedAt)}</dd></div><div><dt>Follow-up</dt><dd>{followUp(action)}</dd></div><div><dt>Attachment Notes</dt><dd>{action.attachmentNotes ?? "None"}</dd></div><div className="actions-taken__details-wide"><dt>Result</dt><dd>{action.result ?? "No result recorded"}</dd></div></dl>;
}

export default function ActionsTakenPanel({ ticketId, role, ticketStatus, assignees = [] }: Props) {
  const [items, setItems] = useState<ActionTaken[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(0); const [totalItems, setTotalItems] = useState(0); const [ticketVersion, setTicketVersion] = useState(1);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0); const [expandedId, setExpandedId] = useState<number | null>(null); const [form, setForm] = useState<"create" | number | null>(null); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState(""); const [ticketInactiveByServer, setTicketInactiveByServer] = useState(false); const [reviewMode, setReviewMode] = useState<ReviewMode>(null); const [reviewMessage, setReviewMessage] = useState("");
  const addButton = useRef<HTMLButtonElement>(null); const editButton = useRef<HTMLButtonElement>(null); const previousTicketStatus = useRef(ticketStatus);
  const operational = role === "IT_STAFF" || role === "ADMINISTRATOR"; const readOnly = isInactive(ticketStatus) || ticketInactiveByServer; const canMutate = operational && !readOnly;
  const load = () => setRefresh((value) => value + 1);

  useEffect(() => { let active = true; setLoading(true); setError(""); fetchActionsTaken(ticketId, page).then((response) => { if (!active) return; setItems(response.items); setTotalPages(response.totalPages); setTotalItems(response.totalItems); setTicketVersion(response.ticketVersion); const refreshed = typeof form === "number" ? response.items.find((item) => item.id === form) : undefined; if (refreshed && refreshed.status !== "DRAFT") { setReviewMode("TERMINAL_STALE"); setReviewMessage("This Action is now terminal and read-only. Review or copy your unsaved changes, then create a new Action for corrections or additional work."); } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Unable to load Actions Taken"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [ticketId, page, refresh]);
  useEffect(() => { if (isInactive(previousTicketStatus.current) && !isInactive(ticketStatus)) { setTicketInactiveByServer(false); if (!reviewMode) setReviewMessage(""); } previousTicketStatus.current = ticketStatus; }, [ticketStatus, reviewMode]);

  const closeForm = () => { const wasCreate = form === "create"; setForm(null); setReviewMode(null); setReviewMessage(""); queueMicrotask(() => (wasCreate ? addButton : editButton).current?.focus()); };
  const submit = async (data: CreateActionTakenInput | UpdateActionTakenInput) => { setSubmitting(true); setNotice(""); try { const result = form === "create" ? await createActionTaken(ticketId, data as CreateActionTakenInput) : await updateActionTaken(ticketId, form!, data as UpdateActionTakenInput); setTicketVersion(result.ticketVersion); setNotice(form === "create" ? "Action saved." : "Action updated."); closeForm(); load(); } catch (reason) { const api = reason instanceof ApiError ? reason : null; if (api?.code === "STALE_UPDATE") { setNotice("This Ticket or Action changed. Review the latest details before saving again."); load(); } else if (api?.code === "ACTION_IMMUTABLE") { setNotice("This Action is read-only. Create a new Action for corrections or additional work."); setReviewMode("ACTION_IMMUTABLE"); setReviewMessage("This Action is read-only. Review or copy your unsaved changes, then create a new Action for corrections or additional work."); load(); } else if (api?.code === "TICKET_NOT_ACTIVE") { setTicketInactiveByServer(true); setNotice("Reopen the Ticket before changing Actions."); setReviewMessage("This Ticket is not active. Review or copy your unsaved changes after reopening the Ticket."); load(); } else { setNotice(api?.message ?? "Unable to save Action. Your draft was preserved; retry when ready."); } } finally { setSubmitting(false); } };
  const selected = typeof form === "number" ? items.find((item) => item.id === form) : undefined;
  const edit = (action: ActionTaken) => canMutate && action.status === "DRAFT" ? <button ref={editButton} type="button" className="btn zg-button zg-button--secondary actions-taken__action actions-taken__action--edit" onClick={() => setForm(action.id)}>Edit Action {action.id}</button> : null;
  const view = (action: ActionTaken) => <button type="button" className="btn zg-button zg-button--secondary actions-taken__action actions-taken__action--view" aria-expanded={expandedId === action.id} onClick={() => setExpandedId((current) => current === action.id ? null : action.id)}>{expandedId === action.id ? `Hide Action ${action.id}` : `View Action ${action.id}`}</button>;

  return <section className="ticket-detail__panel actions-taken" aria-labelledby="actions-taken-heading">
    <div className="actions-taken__heading"><div className="actions-taken__heading-copy"><h2 id="actions-taken-heading">Actions Taken</h2><p>{role === "REQUESTER" ? "Actions Taken are shared with you." : "Actions Taken are shared with the Requester."}</p></div><div className="actions-taken__tools"><span className="actions-taken__count" aria-live="polite">{loading ? "Loading Actions Taken" : `${totalItems} Actions Taken`}</span>{canMutate && form === null ? <button ref={addButton} type="button" className="btn zg-button zg-button--primary actions-taken__add" onClick={() => setForm("create")}>Add Action</button> : null}</div></div>
    {readOnly && operational ? <p className="actions-taken__readonly-note">Reopen the Ticket before changing Actions.</p> : null}{notice ? <p role="status" className="actions-taken__notice">{notice}</p> : null}
    {form === "create" ? <ActionTakenForm mode="create" ticketVersion={ticketVersion} assignees={assignees} submitting={submitting} readOnly={readOnly} reviewMessage={reviewMessage} onSubmit={submit} onClose={closeForm} /> : selected ? <ActionTakenForm mode="edit" action={selected} ticketVersion={ticketVersion} assignees={assignees} submitting={submitting} readOnly={readOnly || reviewMode !== null} reviewMessage={reviewMessage} onSubmit={submit} onClose={closeForm} /> : null}
    {loading ? <Loading message="Loading Actions Taken…" /> : error ? <ErrorState title="Unable to load Actions Taken" message={error} action={<button type="button" className="btn zg-button zg-button--secondary" onClick={load}>Retry</button>} /> : items.length === 0 ? <Empty title="No Actions yet" message="No Actions Taken have been recorded for this Ticket." /> : <>
      <div className="actions-taken__table-wrap"><table className="actions-taken__table"><caption>Actions Taken for this Ticket</caption><thead><tr><th>Action Date/Time</th><th>Description</th><th>Result</th><th>Performed By</th><th>Follow-up</th><th>State</th><th className="actions-taken__actions-column">View/Edit</th></tr></thead><tbody>{items.map((action) => <tr key={action.id}><td>{formatDate(action.actionDateTime)}</td><td>{action.actionDescription}</td><td>{action.result ?? "No result recorded"}</td><td>{action.performedBy?.name ?? "Not performed"}</td><td>{action.followUpRequired ? "Required" : "Not required"}</td><td><span>{action.status}</span>{action.status !== "DRAFT" ? <span className="actions-taken__readonly">Read-only</span> : null}</td><td className="actions-taken__row-actions"><div className="actions-taken__action-group">{view(action)}{edit(action)}</div></td></tr>)}</tbody></table></div>
      <div className="actions-taken__cards">{items.map((action) => <article key={action.id} className="actions-taken__card"><header><strong>Action {action.id}</strong><span>{action.status}{action.status !== "DRAFT" ? " · Read-only" : ""}</span></header><dl><div><dt>Action Date/Time</dt><dd>{formatDate(action.actionDateTime)}</dd></div><div><dt>Description</dt><dd>{action.actionDescription}</dd></div><div><dt>Result</dt><dd>{action.result ?? "No result recorded"}</dd></div><div><dt>Performed By</dt><dd>{action.performedBy?.name ?? "Not performed"}</dd></div><div><dt>Follow-up</dt><dd>{followUp(action)}</dd></div></dl><div className="actions-taken__card-actions">{view(action)}{edit(action)}</div></article>)}</div>
      {expandedId !== null ? (() => { const action = items.find((item) => item.id === expandedId); return action ? <article className="actions-taken__expanded" aria-label={`Action ${action.id} details`}><h3>Action {action.id} details</h3><Details action={action} /></article> : null; })() : null}
      <nav className="actions-taken__pagination" aria-label="Actions Taken pages"><button type="button" className="btn zg-button zg-button--secondary actions-taken__page-button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page} of {totalPages || 1}</span><button type="button" className="btn zg-button zg-button--secondary actions-taken__page-button" disabled={totalPages === 0 || page >= totalPages} onClick={() => setPage((value) => value + 1)}>Next</button></nav>
    </>}
  </section>;
}
