import { useCallback, useEffect, useState } from "react";
import { ApiError, claimStaffTicket, fetchAdminInternalNotes, fetchAdminTicketInspection, fetchUsers, updateAdminTicketPriority, updateStaffTicketOwner, updateStaffTicketStatus, type ActionUserSummary, type StaffTicketStatus, type AdminTicketInspection as Ticket, type InternalNote } from "../api";
import ErrorState from "./ErrorState";
import ActionsTakenPanel from "./ActionsTakenPanel";
import "../styles/admin-ticket-inspection.css";

function formatDate(value: string) { return new Date(value).toLocaleString(); }

export default function AdminTicketInspection({ ticketId }: { ticketId: number }) {
  const [ticket, setTicket] = useState<Ticket | null>(null);
  const [error, setError] = useState("");
  const [priority, setPriority] = useState("MEDIUM");
  const [ownerId, setOwnerId] = useState("");
  const [status, setStatus] = useState<StaffTicketStatus | "">("");
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  const [notes, setNotes] = useState<InternalNote[]>([]);
  const [actionAssignees, setActionAssignees] = useState<ActionUserSummary[]>([]);
  const refreshTicket = useCallback((preserveInputs = false) => { fetchAdminTicketInspection(ticketId).then((value) => { setTicket(value); if (!preserveInputs) { setPriority(value.itPriority); setStatus(value.currentStatus); setOwnerId(value.assignedTo ? String(value.assignedTo.id) : ""); } }).catch((e: Error) => setError(e.message)); }, [ticketId]);
  useEffect(() => { refreshTicket(); fetchAdminInternalNotes(ticketId).then(setNotes).catch((e: Error) => setError(e.message)); fetchUsers().then((users: Array<ActionUserSummary & { isActive?: boolean }>) => setActionAssignees(users.filter((user) => user.isActive !== false && (user.role === "IT_STAFF" || user.role === "ADMINISTRATOR")))).catch(() => setActionAssignees([])); }, [ticketId, refreshTicket]);
  if (error) return <ErrorState title="Unable to load Ticket" message={error} />;
  if (!ticket) return <p className="admin-inspection__loading" role="status">Loading Ticket inspection…</p>;
  const allowedTransitions: Record<StaffTicketStatus, StaffTicketStatus[]> = { NEW: ["OPEN", "CANCELLED"], OPEN: ["IN_PROGRESS", "WAITING_FOR_REQUESTER", "CANCELLED"], IN_PROGRESS: ["WAITING_FOR_REQUESTER", "RESOLVED", "CANCELLED"], WAITING_FOR_REQUESTER: ["IN_PROGRESS", "RESOLVED", "CANCELLED"], RESOLVED: ["CLOSED", "REOPENED"], CLOSED: ["REOPENED"], REOPENED: ["IN_PROGRESS", "WAITING_FOR_REQUESTER", "CANCELLED"], CANCELLED: ["REOPENED"] };
  const recoverConflict = (e: unknown) => { if (e instanceof ApiError && e.status === 409) { setNotice(e.code === "STALE_UPDATE" ? "This Ticket changed. Refresh and review before saving again." : e.message); refreshTicket(true); return true; } return false; };
  const savePriority = async () => { setSaving(true); setNotice(""); try { const updated = await updateAdminTicketPriority(ticketId, priority as never, ticket.version); setTicket({ ...ticket, itPriority: updated.itPriority, version: updated.version }); } catch (e) { if (!recoverConflict(e)) setNotice((e as Error).message); } finally { setSaving(false); } };
  const saveOwner = async () => { setSaving(true); setNotice(""); try { const updated = await updateStaffTicketOwner(ticketId, ownerId ? Number(ownerId) : null, ticket.version); setTicket({ ...ticket, assignedTo: updated.owner, version: updated.version }); } catch (e) { if (!recoverConflict(e)) setNotice((e as Error).message); } finally { setSaving(false); } };
  const claim = async () => { setSaving(true); setNotice(""); try { const updated = await claimStaffTicket(ticketId, ticket.version); setTicket({ ...ticket, assignedTo: updated.owner, version: updated.version }); setOwnerId(updated.owner ? String(updated.owner.id) : ""); } catch (e) { if (!recoverConflict(e)) setNotice((e as Error).message); } finally { setSaving(false); } };
  const saveStatus = async () => { if (!status || status === ticket.currentStatus) return; const confirmation = status === "CANCELLED" ? "Cancel this Ticket? All existing Draft Actions will also be cancelled." : `Confirm transition to ${status}?`; if (["RESOLVED", "CLOSED", "CANCELLED"].includes(status) && !window.confirm(confirmation)) return; setSaving(true); setNotice(""); try { await updateStaffTicketStatus(ticketId, status, ticket.version); refreshTicket(); } catch (e) { if (!recoverConflict(e)) setNotice((e as Error).message); } finally { setSaving(false); } };
  return <main className="admin-inspection">
    <header className="admin-inspection__header"><p className="admin-inspection__eyebrow">Administrator Ticket Inspection</p><h1>Ticket Inspection</h1><p className="admin-inspection__intro">Ticket details are read-only. Administrators can assign ownership, update IT Priority, change Ticket status, and manage Actions Taken.</p></header>
    <section className="admin-inspection__card" aria-labelledby="ticket-information"><h2 id="ticket-information">Ticket information</h2><dl className="admin-inspection__details">
      <div><dt>Ticket Number</dt><dd>{ticket.ticketNumber}</dd></div><div><dt>Summary</dt><dd>{ticket.summary}</dd></div><div className="admin-inspection__detail--wide"><dt>Description</dt><dd>{ticket.description}</dd></div><div><dt>Requester</dt><dd>{ticket.requester.name}</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Requested Priority</dt><dd><span className="admin-inspection__badge">{ticket.requestedPriority}</span></dd></div><div><dt>Current Status</dt><dd><span className="admin-inspection__badge">{ticket.currentStatus}</span></dd></div><div><dt>Owner</dt><dd>{ticket.assignedTo?.name ?? "Unassigned"}</dd></div>
    </dl></section>
    <section className="admin-inspection__card admin-inspection__priority" aria-labelledby="admin-owner"><div><h2 id="admin-owner">Ownership</h2><p>Administrators can claim or assign this Ticket to active operational users.</p></div><div className="admin-inspection__priority-controls"><label htmlFor="admin-ticket-owner">Owner</label><select id="admin-ticket-owner" value={ownerId} disabled={saving} onChange={(e) => setOwnerId(e.target.value)}><option value="">Unassigned</option>{actionAssignees.map((user) => <option key={user.id} value={user.id}>{user.name} ({user.role})</option>)}</select>{!ticket.assignedTo ? <button type="button" className="btn zg-button zg-button--secondary" disabled={saving} onClick={() => void claim()}>Claim ticket</button> : null}<button type="button" className="btn zg-button zg-button--primary" disabled={saving} onClick={() => void saveOwner()}>Save owner</button></div></section>
    <section className="admin-inspection__card admin-inspection__priority"><div><h2>IT Priority</h2><p>Administrators can update IT Priority and apply permitted Ticket status transitions.</p></div><div className="admin-inspection__priority-controls"><label htmlFor="admin-it-priority">IT Priority</label><select id="admin-it-priority" value={priority} disabled={saving} onChange={(e) => setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select><button type="button" className="btn zg-button zg-button--primary" disabled={saving} onClick={() => void savePriority()}>{saving ? "Saving…" : "Save IT Priority"}</button></div>{error && <p className="admin-inspection__inline-error" role="alert">{error}</p>}</section>
    {notice && <p className="admin-inspection__inline-error" role="alert">{notice}</p>}
    <section className="admin-inspection__card admin-inspection__priority" aria-labelledby="admin-workflow"><div><h2 id="admin-workflow">Workflow</h2><p>Only permitted next statuses are available. Resolve requires a Completed Action with a Result and no Draft Actions.</p>{(allowedTransitions[ticket.currentStatus] ?? []).includes("RESOLVED") && !ticket.resolutionReady ? <p>Resolve is unavailable until the Action gate is met. <a href="#actions-taken-heading">Review Actions Taken</a>.</p> : null}</div><div className="admin-inspection__priority-controls"><label htmlFor="admin-ticket-status">Status</label><select id="admin-ticket-status" value={status} disabled={saving} onChange={(e) => setStatus(e.target.value as StaffTicketStatus)}><option value={ticket.currentStatus}>{ticket.currentStatus}</option>{(allowedTransitions[ticket.currentStatus] ?? []).filter((next) => next !== "RESOLVED" || ticket.resolutionReady).map((next) => <option key={next} value={next}>{next}</option>)}</select><button type="button" className="btn zg-button zg-button--primary" disabled={saving || status === ticket.currentStatus} onClick={() => void saveStatus()}>{saving ? "Saving…" : "Save status"}</button></div></section>
    {ticket.requesterResolutionIndicatedAt ? <p className="alert alert-info">Requester indicated that the problem appears resolved on {formatDate(ticket.requesterResolutionIndicatedAt)}.</p> : null}
    <section className="admin-inspection__card" aria-labelledby="public-comments"><h2 id="public-comments">Public Comments</h2>{ticket.publicComments?.length ? ticket.publicComments.map((comment) => <article className="admin-inspection__message" key={comment.id}><p>{comment.body}</p><small>{comment.author.name} · {formatDate(comment.createdAt)}</small></article>) : <p className="admin-inspection__empty">No public comments.</p>}</section>
    <section className="admin-inspection__card admin-inspection__notes" aria-labelledby="internal-notes"><h2 id="internal-notes">Internal Notes</h2><p className="admin-inspection__readonly">Internal communications · read-only</p>{notes.length ? notes.map((note) => <article className="admin-inspection__message" key={note.id}><p>{note.body}</p><small>{note.author.name} · {formatDate(note.createdAt)}</small></article>) : <p className="admin-inspection__empty">No internal notes.</p>}</section>
    <ActionsTakenPanel ticketId={ticket.id} role="ADMINISTRATOR" ticketStatus={ticket.currentStatus} assignees={actionAssignees} onTicketRefreshRequested={refreshTicket} />
  </main>;
}
